name: Build & publish undergraduate guide

on:
  push:
    branches: [ main ]
    paths:
      - "Guide_1er_cycle_2025_VF.docx"
      - "assets/**"
      - ".github/workflows/build-guide.yml"
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      # Install tools + Times New Roman for faithful PDF
      - name: Install converters & fonts
        run: |
          sudo apt-get update
          sudo apt-get install -y libreoffice pandoc fontconfig software-properties-common
          sudo add-apt-repository multiverse -y
          sudo apt-get update
          echo "ttf-mscorefonts-installer msttcorefonts/accepted-mscorefonts-eula select true" | sudo debconf-set-selections
          sudo apt-get install -y ttf-mscorefonts-installer
          sudo fc-cache -f -v
          fc-list | grep -i "Times New Roman" || true

      - name: Prepare dist and copy assets
        run: |
          mkdir -p dist/assets
          cp -r assets/* dist/assets/ || true

      # Optional: surface build date in the HTML footer
      - name: Set build date
        run: echo "BUILD_DATE=$(date -u +%Y-%m-%d)" >> $GITHUB_ENV

      # DOCX → PDF (desktop), embed fonts & bookmarks
      - name: Convert DOCX to PDF
        run: |
          libreoffice --headless \
            --convert-to "pdf:writer_pdf_Export:EmbedStandardFonts=true;ExportBookmarks=true;SelectPdfVersion=1" \
            "Guide_1er_cycle_2025_VF.docx" \
            --outdir dist

      # (Optional) Set PDF metadata (Title/Author/Subject)
      - name: Install exiftool
        run: sudo apt-get update && sudo apt-get install -y libimage-exiftool-perl
      - name: Set PDF metadata
        env:
          PDF_TITLE: "Guide du programme d'histoire – UQAM"
          PDF_AUTHOR: "Département d’histoire, UQAM"
          PDF_SUBJECT: "Guide du 1er cycle (B.A., majeure, mineures, certificats)"
        run: |
          exiftool -overwrite_original \
            -Title="$PDF_TITLE" \
            -Author="$PDF_AUTHOR" \
            -Subject="$PDF_SUBJECT" \
            -Keywords="UQAM, Histoire, Premier cycle, Guide" \
            dist/Guide_1er_cycle_2025_VF.pdf
          exiftool -Title -Author -Subject dist/Guide_1er_cycle_2025_VF.pdf || true

      # Create a Pandoc HTML template on the fly (no missing file issues)
      - name: Create Pandoc HTML template
        run: |
          mkdir -p assets
          printf '%s\n' \
'<!doctype html>' \
'<html lang="$lang$">' \
'<head>' \
'  <meta charset="utf-8">' \
'  <meta name="viewport" content="width=device-width, initial-scale=1">' \
'  <title>$title$</title>' \
'  $for(css)$<link rel="stylesheet" href="$css$">$endfor$' \
'</head>' \
'<body id="top">' \
'<header class="site-header">' \
'  <h1>$title$</h1>' \
'  <nav class="doc-actions"><a class="btn" href="Guide_1er_cycle_2025_VF.pdf">PDF imprimable</a></nav>' \
'</header>' \
'' \
'$if(toc)$' \
'<details class="toc" open>' \
'  <summary>Sommaire</summary>' \
'  $toc$' \
'</details>' \
'$endif$' \
'' \
'$body$' \
'' \
'<footer class="site-footer">' \
'  <p>Dernière mise à jour : $date$</p>' \
'  <p><a href="#top">Retour en haut</a></p>' \
'</footer>' \
'</body>' \
'</html>' \
> assets/pandoc.html5

      # DOCX → HTML (mobile) with ToC, numbered sections, and template
      - name: Convert DOCX to HTML (Pandoc)
        run: |
          pandoc "Guide_1er_cycle_2025_VF.docx" \
                 -s -t html5 \
                 --template=assets/pandoc.html5 \
                 --metadata title="Guide du programme d'histoire – UQAM" \
                 --metadata lang=fr \
                 --metadata date="${BUILD_DATE}" \
                 --toc --toc-depth=3 --number-sections \
                 --css=assets/uqam-guide.css \
                 -o dist/index.html

      # Publish to GitHub Pages (gh-pages branch)
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          publish_dir: dist
          publish_branch: gh-pages
          github_token: ${{ secrets.GITHUB_TOKEN }}
